name: CI Pipeline

on:
  pull_request:
    branches: [ main, uat, test, dev ]
  push:
    branches: [ main, uat, test, dev ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: Frontend
      - run: npm run dev -- --dry-run
        working-directory: Frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: Backend
      - run: npx nodemon index.js --exitcrash
        working-directory: Backend

  admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: admin
      - run: npm run dev -- --dry-run
        working-directory: admin