name: Lint & Format Check

on:
  pull_request:
    branches: [ main, uat, test, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: Frontend
      - run: npm run lint
        working-directory: Frontend
      - run: npm run format
        working-directory: Frontend
